spring.application.name=MinecraftModCatalog
spring.datasource.url=jdbc:postgresql://ep-hidden-dream-azi9yi8z-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_2Cj6ApPXkzTt&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_2Cj6ApPXkzTt
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
